schemas:
  bootstrap: 8000
  romaroma_theme: 8000
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://module-lvl-0.docksal/themes/contrib/bootstrap/favicon.ico'
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: ''
  url: ''
  use_default: true
